### ISSUE TITLE
auto refresh needed

### ISSUE THREAD

**Issue by wojosc** [tueit/pdf_on_submit#1]
when submitting a DocType a refresh is needed to display/attach the PDF. A user will need to refresh via e.g. F5 to see the attachment. This is irritating when for example the document is sent via email just after submitting as it will not show up.

Can it be done that a refresh is run just after the DocType has been submitted?

**Comment by barredterra** [comment]
This is already implemented ;)

https://github.com/tueit/pdf_on_submit/commit/4f59e5bd15c16f05b601f219311def8e06cc350f

**Comment by wojosc** [comment]
Hi @barredterra just tested this on our new instance v12. Works perfectly. The user feedback you built in is good!
